services:
  agents:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crypto_agents
    command: python3 main.py
    volumes:
      - ./data:/app/data

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crypto_dashboard
    command: python3 dashboard/app.py
    ports:
      - "8050:8050"
    volumes:
      - ./data:/app/data
