pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                // Change 'docker compose' to 'docker-compose'
                sh 'docker-compose build'
            }
        }

        stage('Run') {
            steps {
                // Change 'docker compose' to 'docker-compose'
                sh 'docker-compose up -d'
            }
        }
    }
}
